name: Build, Test, and Package H26Forge

on:
  push:
    branches: [ "release" ]
    #paths:
    #  - '**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            bin: h26forge.exe
            os: windows-latest
            name: windows-x86_64
          - target: x86_64-unknown-linux-gnu
            bin: h26forge
            os: ubuntu-latest
            name: linux-x86_64
          - target: aarch64-apple-darwin
            bin: h26forge
            os: macos-13
            name: mac-aarch64
          - target: x86_64-apple-darwin
            bin: h26forge
            os: macos-13
            name: mac-x86_64
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Add target
      run: rustup target add ${{ matrix.target }}
    - name: Build
      run: cargo build --release --verbose --target ${{ matrix.target }}
    - name: Run tests
      run: cargo test --verbose
    - name: Move binary
      run: cp target/${{ matrix.target }}/release/${{ matrix.bin }} .
    - name: Package output
      run: tar -czvf h26forge-${{ matrix.name }}.tar.gz docs config input_vids transforms scripts README.md ${{ matrix.bin }}
    - uses: actions/upload-artifact@v3
      with:
        name: h26forge-${{ matrix.name }}
        path: |
          h26forge-${{ matrix.name }}.tar.gz
    - name: Set tag name
      id: vars
      run:  |
            if [ "$RUNNER_OS" == "Windows" ]; then
                  echo "::set-output name=year_month_day::$(date +'%Y-%m-%d')"
            else
                  echo "year_month_day=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
            fi
      shell: bash
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "h26forge-${{ matrix.name }}.tar.gz"
        bodyFile: RELEASE.md
        tag: ${{ steps.vars.outputs.year_month_day }}
        commit: main
        allowUpdates: true
        makeLatest: true